// Builds and downloads a one-university recommendation report as a PDF
export async function downloadRecommendationPdf(uni) {
  const { jsPDF } = await import("jspdf"); // loaded only when someone saves a PDF
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const margin = 50;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const textWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const paragraph = (text, { size = 11, bold = false, color = [40, 40, 40], gap = 6 } = {}) => {
    if (!text) return;
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lineHeight = size * 1.35;
    doc.splitTextToSize(String(text), textWidth).forEach(line => {
      ensureSpace(lineHeight);
      doc.text(line, margin, y);
      y += lineHeight;
    });
    y += gap;
  };

  const heading = (text) => {
    ensureSpace(36);
    y += 8;
    paragraph(text, { size: 13, bold: true, color: [79, 60, 97], gap: 2 });
  };

  const list = (items) => {
    (items || []).forEach(item => paragraph(`•  ${item}`, { gap: 2 }));
    y += 4;
  };

  // Header band
  doc.setFillColor(11, 6, 32);
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("AI University Recommendation", margin, 44);
  y = 100;

  paragraph(uni.name, { size: 20, bold: true, color: [11, 6, 32], gap: 2 });
  paragraph([uni.city, uni.province].filter(Boolean).join(", "), { color: [110, 110, 110], gap: 2 });
  paragraph([uni.type, uni.rank, uni.matchScore != null ? `Match score: ${uni.matchScore}%` : null].filter(Boolean).join("  •  "), { bold: true, color: [124, 58, 237] });

  if (uni.fee) { heading("Estimated Fee"); paragraph(uni.fee); }
  if (uni.reason) { heading("Recommendation Reason"); paragraph(uni.reason); }
  if (uni.aiAnalysis) { heading("AI Analysis"); paragraph(uni.aiAnalysis); }
  if (uni.pros?.length) { heading("Pros"); list(uni.pros); }
  if (uni.cons?.length) { heading("Cons"); list(uni.cons); }

  ensureSpace(30);
  paragraph(`Generated by AikApply on ${new Date().toLocaleDateString()}`, { size: 9, color: [150, 150, 150] });

  const fileName = `${(uni.name || "recommendation").replace(/[^a-z0-9]+/gi, "_").replace(/^_|_$/g, "")}_recommendation.pdf`;
  doc.save(fileName);
}
