"""
Django settings for aikapply project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-d9p9%et36q+0(uv+tya3)nfgg3=z^uq&ioabg0#p!p7ct#-iev',  # dev-only fallback
)

# SECURITY WARNING: don't run with debug turned on in production!
# Local development: DEBUG on by default. The Docker deployment sets DJANGO_DEBUG=0.
DEBUG = os.getenv('DJANGO_DEBUG', '1') == '1'

def _env_list(name, default=""):
    return [v.strip() for v in os.getenv(name, default).split(",") if v.strip()]

# e.g. DJANGO_ALLOWED_HOSTS="muaaz-butt-aikapply.hf.space,localhost"
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# Add CORS and CSRF settings

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",  # React dev URL
]
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_NAME = "csrftoken"
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173",
                        "http://127.0.0.1:5173",
                        "http://127.0.0.1:3000/apply",
                        "http://127.0.0.1:3000/",
                        "http://127.0.0.1:4000/",
                        "http://127.0.0.1:4000/uet"
                        ] + _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Set DJANGO_ALLOW_IFRAME=1 only for hosts that show the app inside an iframe
# (e.g. Hugging Face Spaces): cookies then need SameSite=None and framing must be allowed.
ALLOW_IFRAME = os.getenv('DJANGO_ALLOW_IFRAME') == '1'

if not DEBUG:
    # Production is served over HTTPS behind a proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    if ALLOW_IFRAME:
        SESSION_COOKIE_SAMESITE = 'None'
        CSRF_COOKIE_SAMESITE = 'None'

# Auto-apply runs a real browser (needs ~1 GB RAM). Hosts too small for it set AUTO_APPLY_ENABLED=0.
AUTO_APPLY_ENABLED = os.getenv('AUTO_APPLY_ENABLED', '1') == '1'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    "corsheaders",
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'student_data',
    'ai_mapping',
    'api',
    'automation_engine',
    'recommendations',
    'automation_pipline',
    'deadline',

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves static files + the built React app
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG and ALLOW_IFRAME:
    # Allow the app to be embedded in its host's page (e.g. a Hugging Face Space)
    MIDDLEWARE.remove('django.middleware.clickjacking.XFrameOptionsMiddleware')

ROOT_URLCONF = 'aikapply.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aikapply.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Production uses Postgres (e.g. Neon) from DATABASE_URL. Local development keeps
# SQLite even if DATABASE_URL is in .env, so local testing never touches real data.
if not DEBUG and os.getenv('DATABASE_URL'):
    import dj_database_url
    DATABASES['default'] = dj_database_url.parse(
        os.environ['DATABASE_URL'], conn_max_age=600, ssl_require=True,
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Built React app (fyp-frontend1/dist), copied here by the Dockerfile.
# WhiteNoise serves its files (/assets/..., favicon) from the site root.
FRONTEND_DIST = Path(os.getenv('FRONTEND_DIST', BASE_DIR / 'frontend_dist'))
if FRONTEND_DIST.is_dir():
    WHITENOISE_ROOT = FRONTEND_DIST

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        # optionally, keep JWT if needed
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


SIMPLE_JWT = {
    "BLACKLIST_AFTER_ROTATION": True,
}

AUTH_USER_MODEL = 'accounts.User'
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# Credentials auto-apply uses on portals that need a login.
# Defaults match the demo portal at /demo-portals/fast-nuces/.
PORTAL_EMAIL = os.getenv('PORTAL_EMAIL', 'student')
PORTAL_PASSWORD = os.getenv('PORTAL_PASSWORD', 'au2024')